// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owwtcjvkmwykcjqgdlsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93d3RjanZrbXd5a2NqcWdkbHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzQ3MDUsImV4cCI6MjA2MDA1MDcwNX0.1yiZ7jn6oV3ktXoiZRJYJPl2ETZvbxbO_51bzv1GyVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);